import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { GenerateHealthyMealPlanOutput } from '@/ai/schemas/healthy-meal-plan-schemas';

export type PDFRecipeData = {
  dishName: string;
  cookingTime: string;
  servings: number;
  difficulty: string;
  estimatedCost: number;
  ingredients: { name: string; quantity: string; cost?: number }[];
  instructions: string[];
  storageInstructions?: string[];
  reheatingInstructions?: string[];
};

const BRAND_COLOR = [244, 162, 26]; // #F4A21A

function addBranding(doc: jsPDF, y: number) {
  doc.setTextColor(BRAND_COLOR[0], BRAND_COLOR[1], BRAND_COLOR[2]);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.text("CookMitra AI", 14, y);
}

function addFooter(doc: jsPDF) {
  const pageCount = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(10);
    doc.setTextColor(150, 150, 150);
    doc.setFont('helvetica', 'normal');
    doc.text("Made with love in India", 105, doc.internal.pageSize.getHeight() - 10, { align: 'center' });
  }
}

export const generateMealPlanPDF = (plan: GenerateHealthyMealPlanOutput) => {
  const doc = new jsPDF();
  let y = 15;

  addBranding(doc, y);
  y += 12;

  doc.setTextColor(0, 0, 0);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(22);
  doc.text("Your Weekly Meal Plan", 105, y, { align: 'center' });
  y += 10;
  
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text("Here is a balanced Indian meal plan generated by AI based on your preferences.", 105, y, { align: 'center'});
  y += 15;

  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text("Weekly Summary", 14, y);
  y += 8;

  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  const summaryLines = [
    `- Avg. Calories/Day: ${plan.weeklySummary.avgCaloriesPerDay} kcal`,
    `- Avg. Protein/Day: ${plan.weeklySummary.avgProteinPerDay} g`,
    `- Est. Cost: Rs. ${plan.weeklySummary.estimatedCost}`,
    `- Healthy Days: ${plan.weeklySummary.healthyDays} / 7`,
  ];
  doc.text(summaryLines.join('\n'), 14, y);
  y += 30;

  plan.week.forEach(dayPlan => {
    if (y > doc.internal.pageSize.getHeight() - 60) {
      doc.addPage();
      y = 15;
    }

    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text(dayPlan.day, 14, y);

    autoTable(doc, {
      startY: y + 2,
      head: [["Meal", "Food", "Calories (kcal)", "Protein (g)", "Carbs (g)", "Fats (g)"]],
      body: dayPlan.meals.map(meal => [meal.type, meal.food, meal.calories, meal.protein, meal.carbs, meal.fats]),
      theme: 'grid',
      headStyles: { fillColor: BRAND_COLOR as any },
      styles: { fontSize: 9 },
      didDrawPage: (data) => {
        y = data.cursor?.y ?? 15;
      }
    });
    
    y = (doc as any).lastAutoTable.finalY + 10;
  });

  if (y > doc.internal.pageSize.getHeight() - 30) {
      doc.addPage();
      y = 15;
  }
  doc.setFontSize(10);
  doc.setTextColor(0, 0, 0);
  doc.setFont('helvetica', 'italic');
  const splitDisclaimer = doc.splitTextToSize(plan.disclaimer, 180);
  doc.text(splitDisclaimer, 14, y);

  addFooter(doc);
  doc.save('CookMitra-Meal-Plan.pdf');
};

export const generateRecipePDF = (recipe: PDFRecipeData) => {
  const doc = new jsPDF();
  let y = 15;

  addBranding(doc, y);
  y += 12;

  // Title
  doc.setTextColor(0, 0, 0);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(24);
  const splitTitle = doc.splitTextToSize(recipe.dishName, 180);
  doc.text(splitTitle, 14, y);
  y += (splitTitle.length * 10);

  // Info Row
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 100, 100);
  const infoText = `Cooking Time: ${recipe.cookingTime} | Serves: ${recipe.servings} | Difficulty: ${recipe.difficulty} | Est. Cost: Rs. ${recipe.estimatedCost}`;
  doc.text(infoText, 14, y);
  y += 12;

  // Ingredients Section
  doc.setTextColor(0, 0, 0);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.text("Ingredients", 14, y);
  y += 6;

  autoTable(doc, {
    startY: y,
    head: [["Ingredient", 'Qty', 'Cost (Rs.)']],
    body: recipe.ingredients.map(ing => [ing.name, ing.quantity, ing.cost || '-']),
    theme: 'striped',
    headStyles: { fillColor: BRAND_COLOR as any },
    styles: { fontSize: 10 },
    didDrawPage: (data) => {
      y = data.cursor?.y ?? 15;
    }
  });

  y = (doc as any).lastAutoTable.finalY + 15;

  // Instructions Section
  if (y > doc.internal.pageSize.getHeight() - 40) {
    doc.addPage();
    y = 15;
  }
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.text("Instructions", 14, y);
  y += 8;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  recipe.instructions.forEach((step, i) => {
    const stepText = `${i + 1}. ${step}`;
    const lines = doc.splitTextToSize(stepText, 180);
    
    if (y + (lines.length * 7) > doc.internal.pageSize.getHeight() - 20) {
      doc.addPage();
      y = 15;
    }
    
    doc.text(lines, 14, y);
    y += (lines.length * 7) + 2;
  });

  // Batch Instructions
  if (recipe.storageInstructions || recipe.reheatingInstructions) {
    y += 10;
    
    if (recipe.storageInstructions) {
      if (y > doc.internal.pageSize.getHeight() - 40) { doc.addPage(); y = 15; }
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(12);
      doc.text("Storage Instructions", 14, y);
      y += 6;
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      recipe.storageInstructions.forEach(line => {
        const wrapped = doc.splitTextToSize(`• ${line}`, 180);
        doc.text(wrapped, 14, y);
        y += (wrapped.length * 5) + 1;
      });
      y += 5;
    }

    if (recipe.reheatingInstructions) {
      if (y > doc.internal.pageSize.getHeight() - 40) { doc.addPage(); y = 15; }
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(12);
      doc.text("Reheating Instructions", 14, y);
      y += 6;
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      recipe.reheatingInstructions.forEach(line => {
        const wrapped = doc.splitTextToSize(`• ${line}`, 180);
        doc.text(wrapped, 14, y);
        y += (wrapped.length * 5) + 1;
      });
    }
  }

  addFooter(doc);
  doc.save(`${recipe.dishName.replace(/\s+/g, '-')}-Recipe.pdf`);
};
