import { Recipe } from './types';

export const baseRecipes: Recipe[] = [
  {
    id: "chicken-biryani",
    menuCategory: "Rice & Biryani",
    name: "Chicken Biryani",
    description: "Aromatic basmati rice layered with spiced chicken and caramelized onions. A classic Indian one-pot meal.",
    type: "Non-Vegetarian",
    time: 45,
    servings: 4,
    difficulty: "Medium",
    cost: 350,
    popularity: 0.9,
    tags: ["North Indian", "Popular", "Weeknight Dinner", "Spicy"],
    healthTags: ["anemia-friendly", "immunity-boosting"],
    ingredients: [
      { id: "chicken", name: "Chicken", qty: "0.75 kg", price: 250, available: true },
      { id: "basmati_rice", name: "Basmati Rice", qty: "1 kg", price: 100, available: true },
      { id: "onion", name: "Onion", qty: "4", price: 20, available: true },
      { id: "yogurt", name: "Yogurt", qty: "1 cup", price: 25, available: false },
      { id: "ginger_garlic_paste", name: "Ginger-Garlic Paste", qty: "2 tbsp", price: 10, available: true },
      { id: "garam_masala", name: "Garam Masala", qty: "1 tbsp", price: 22, available: false },
    ],
    steps: [
      "Marinate chicken with yogurt, ginger-garlic paste, green chilies, and half the garam masala for 30 minutes.",
      "Soak basmati rice for 30 minutes, then parboil until 70% cooked.",
      "In a separate pan, fry sliced onions until golden brown (birista).",
      "Cook the marinated chicken in a heavy-bottomed pot until it's tender.",
      "Layer the parboiled rice over the cooked chicken. Sprinkle with fried onions, mint leaves, and remaining garam masala.",
      "Cover the pot with a tight lid and cook on low heat (dum) for 15-20 minutes.",
      "Gently fluff the biryani with a fork and serve hot with raita.",
    ]
  },
  {
    id: "butter-chicken",
    menuCategory: "Curries & Gravies",
    name: "Butter Chicken",
    description: "Creamy tomato-based curry with tender chicken pieces. A restaurant-style classic that's easy to make at home.",
    type: "Non-Vegetarian",
    time: 35,
    servings: 4,
    difficulty: "Easy",
    cost: 280,
    popularity: 0.95,
    tags: ["North Indian", "Punjabi", "Popular", "Weeknight Dinner", "Comfort Food"],
    healthTags: ["pregnancy-friendly"],
    ingredients: [
        { id: "chicken", name: "Chicken", qty: "500g", price: 150, available: true },
        { id: "tomato", name: "Tomato", qty: "4", price: 20, available: true },
        { id: "onion", name: "Onion", qty: "2", price: 10, available: true },
        { id: "ginger_garlic_paste", name: "Ginger-Garlic Paste", qty: "1 tbsp", price: 5, available: true },
        { id: "cream", name: "Cream", qty: "1/2 cup", price: 40, available: false },
        { id: "butter", name: "Butter", qty: "2 tbsp", price: 20, available: true },
    ],
    steps: [
      "Marinate chicken with spices.",
      "Make a tomato and onion gravy.",
      "Cook chicken in the gravy.",
      "Add cream and butter.",
      "Simmer until chicken is cooked through.",
    ]
  },
  {
    id: "paneer-tikka-masala",
    menuCategory: "Protein Specialties",
    name: "Paneer Tikka Masala",
    description: "Creamy tomato-based curry with marinated paneer cubes. A vegetarian delight perfect for any occasion.",
    type: "Vegetarian",
    time: 40,
    servings: 4,
    difficulty: "Medium",
    cost: 220,
    popularity: 0.88,
    tags: ["North Indian", "Vegetarian", "Punjabi", "Popular", "Weeknight Dinner", "Spicy"],
    healthTags: ["pregnancy-friendly", "immunity-boosting"],
    ingredients: [
        { id: "paneer", name: "Paneer", qty: "250g", price: 100, available: true },
        { id: "tomato", name: "Tomato", qty: "4", price: 20, available: true },
        { id: "onion", name: "Onion", qty: "2", price: 10, available: true },
        { id: "ginger_garlic_paste", name: "Ginger-Garlic Paste", qty: "1 tbsp", price: 5, available: true },
        { id: "cream", name: "Cream", qty: "1/2 cup", price: 40, available: false },
        { id: "yogurt", name: "Yogurt", qty: "1/4 cup", price: 10, available: true },
    ],
    steps: [
      "Marinate paneer with yogurt and spices.",
      "Grill or pan-fry the paneer.",
      "Prepare a creamy tomato gravy.",
      "Add paneer tikka to the gravy.",
      "Simmer for a few minutes and serve.",
    ]
  },
  {
    id: "chole-bhature",
    menuCategory: "Breads",
    name: "Chole Bhature",
    description: "Deep-fried fluffy bread served with spiced chickpea curry. A North Indian street food favorite.",
    type: "Vegetarian",
    time: 60,
    servings: 2,
    difficulty: "Medium",
    cost: 150,
    popularity: 0.8,
    tags: ["North Indian", "Street Food", "Vegetarian", "Punjabi", "Monsoon Snack", "Spicy"],
    healthTags: ["anemia-friendly"],
    ingredients: [
        { id: "chickpeas", name: "Chickpeas", qty: "1 cup", price: 30, available: true },
        { id: "all_purpose_flour", name: "All-purpose flour", qty: "2 cups", price: 20, available: true },
        { id: "yogurt", name: "Yogurt", qty: "1/2 cup", price: 10, available: true },
        { id: "onion", name: "Onion", qty: "2", price: 10, available: true },
        { id: "tomato", name: "Tomato", qty: "2", price: 10, available: true },
        { id: "spices", name: "Spices", qty: "various", price: 20, available: false },
    ],
    steps: [
        "Soak chickpeas overnight and cook until tender.",
        "Prepare a spiced tomato-onion gravy.",
        "Add cooked chickpeas to the gravy and simmer.",
        "Knead a soft dough for bhature and let it rest.",
        "Roll and deep-fry the bhature until golden and puffed.",
        "Serve hot with chole.",
    ]
  },
  {
    id: "sambar",
    menuCategory: "Curries & Gravies",
    name: "Sambar",
    description: "A tangy lentil and vegetable stew from South India. Served with rice, idli, or dosa.",
    type: "Vegetarian",
    time: 30,
    servings: 4,
    difficulty: "Easy",
    cost: 120,
    popularity: 0.85,
    tags: ["South Indian", "Vegetarian", "Tamil Nadu", "Kerala", "Karnataka", "Andhra Pradesh", "Weeknight Dinner"],
    healthTags: ["digestive-friendly", "weight-management", "heart-healthy", "diabetes-friendly"],
    ingredients: [
        { id: "toor_dal", name: "Toor Dal", qty: "1 cup", price: 40, available: true },
        { id: "mixed_vegetables", name: "Mixed Vegetables", qty: "2 cups", price: 30, available: true },
        { id: "tamarind", name: "Tamarind", qty: "small piece", price: 10, available: true },
        { id: "sambar_powder", name: "Sambar Powder", qty: "2 tbsp", price: 15, available: false },
        { id: "onion", name: "Onion", qty: "1", price: 5, available: true },
        { id: "tomato", name: "Tomato", qty: "1", price: 5, available: true },
    ],
    steps: [
        "Cook toor dal with turmeric until soft.",
        "Cook vegetables separately.",
        "Mix dal and vegetables.",
        "Add tamarind extract and sambar powder.",
        "Prepare tempering and add it to the sambar.",
        "Simmer for 10 minutes.",
    ]
  },
  {
    id: "masala-dosa",
    menuCategory: "Breads",
    name: "Masala Dosa",
    description: "Crispy crepe made from fermented rice and lentils, filled with a spiced potato filling.",
    type: "Vegetarian",
    time: 20,
    servings: 4,
    difficulty: "Medium",
    cost: 100,
    popularity: 0.92,
    tags: ["South Indian", "Street Food", "Vegetarian", "Karnataka", "Tamil Nadu", "Breakfast"],
    healthTags: ["digestive-friendly"],
    ingredients: [
        { id: "dosa_batter", name: "Dosa Batter", qty: "4 cups", price: 40, available: true },
        { id: "potato", name: "Potato", qty: "4", price: 20, available: true },
        { id: "onion", name: "Onion", qty: "2", price: 10, available: true },
        { id: "green_chili", name: "Green Chilies", qty: "2", price: 2, available: true },
        { id: "mustard_seeds", name: "Mustard Seeds", qty: "1 tsp", price: 2, available: false },
        { id: "turmeric_powder", name: "Turmeric Powder", qty: "1/2 tsp", price: 2, available: true },
    ],
    steps: [
        "Prepare the potato filling by cooking potatoes with spices.",
        "Heat a tawa or griddle.",
        "Spread a ladleful of dosa batter to make a thin crepe.",
        "Add the potato filling in the center.",
        "Fold the dosa and serve hot with chutney and sambar.",
    ]
  },
  {
    id: "dal-makhani",
    menuCategory: "Curries & Gravies",
    name: "Dal Makhani",
    description: "A rich and creamy lentil curry made with black gram and kidney beans, a specialty from Punjab.",
    type: "Vegetarian",
    time: 90,
    servings: 4,
    difficulty: "Medium",
    cost: 250,
    popularity: 0.87,
    tags: ["North Indian", "Punjabi", "Vegetarian", "Weeknight Dinner", "Comfort Food"],
    healthTags: ["anemia-friendly"],
    ingredients: [
        { id: "urad_dal", name: "Black Gram (Urad Dal)", qty: "1 cup", price: 50, available: true },
        { id: "rajma", name: "Kidney Beans (Rajma)", qty: "1/4 cup", price: 20, available: true },
        { id: "onion", name: "Onion", qty: "2", price: 10, available: true },
        { id: "tomato", name: "Tomato Puree", qty: "1 cup", price: 30, available: true },
        { id: "ginger_garlic_paste", name: "Ginger-Garlic Paste", qty: "1 tbsp", price: 5, available: true },
        { id: "cream", name: "Cream", qty: "1/4 cup", price: 25, available: false },
        { id: "butter", name: "Butter", qty: "2 tbsp", price: 20, available: true },
    ],
    steps: [
        "Soak black gram and kidney beans overnight.",
        "Pressure cook the lentils until very soft.",
        "In a pan, sauté onions until golden brown.",
        "Add ginger-garlic paste and tomato puree, cook until it forms a paste.",
        "Add spices and mix well.",
        "Add the cooked lentils to the pan and simmer for at least 30 minutes on low heat.",
        "Finish with cream and a dollop of butter.",
        "Serve hot with naan or rice.",
    ]
  },
  {
    id: "rajma-chawal",
    menuCategory: "Curries & Gravies",
    name: "Rajma Chawal",
    description: "A comforting North Indian dish of red kidney beans in a thick gravy served with rice.",
    type: "Vegetarian",
    time: 45,
    servings: 4,
    difficulty: "Easy",
    cost: 180,
    popularity: 0.78,
    tags: ["North Indian", "Punjabi", "Vegetarian", "Weeknight Dinner", "Comfort Food"],
    healthTags: ["anemia-friendly", "weight-management", "heart-healthy"],
    ingredients: [
        { id: "rajma", name: "Kidney Beans (Rajma)", qty: "1 cup", price: 30, available: true },
        { id: "basmati_rice", name: "Basmati Rice", qty: "1.5 cups", price: 120, available: true },
        { id: "onion", name: "Onion", qty: "2", price: 10, available: true },
        { id: "tomato", name: "Tomato", qty: "3", price: 15, available: true },
        { id: "ginger_garlic_paste", name: "Ginger-Garlic Paste", qty: "1 tbsp", price: 5, available: true },
    ],
    steps: [
        "Soak kidney beans overnight and pressure cook until tender.",
        "Cook basmati rice separately.",
        "Prepare a gravy with onions, tomatoes, and ginger-garlic paste.",
        "Add cooked kidney beans to the gravy and simmer for 15-20 minutes.",
        "Serve hot with rice."
    ]
  },
  {
    id: "palak-paneer",
    menuCategory: "Curries & Gravies",
    name: "Palak Paneer",
    description: "A classic vegetarian dish from North India consisting of paneer in a thick paste made from puréed spinach.",
    type: "Vegetarian",
    time: 30,
    servings: 3,
    difficulty: "Easy",
    cost: 200,
    popularity: 0.86,
    tags: ["North Indian", "Punjabi", "Vegetarian", "Healthy", "Weeknight Dinner"],
    healthTags: ["diabetes-friendly", "anemia-friendly", "pregnancy-friendly", "pcos-friendly", "immunity-boosting"],
    ingredients: [
        { id: "paneer", name: "Paneer", qty: "200g", price: 100, available: true },
        { id: "spinach", name: "Spinach", qty: "1 large bunch", price: 30, available: true },
        { id: "onion", name: "Onion", qty: "1", price: 5, available: true },
        { id: "tomato", name: "Tomato", qty: "2", price: 10, available: true },
        { id: "cream", name: "Cream", qty: "2 tbsp", price: 20, available: false },
    ],
    steps: [
        "Blanch and puree spinach.",
        "Sauté onions and tomatoes, then add the spinach puree.",
        "Add paneer cubes and simmer for 10 minutes.",
        "Stir in cream before serving.",
        "Serve hot with roti or naan."
    ]
  },
];
